- --my_project:
  - --settings:
    - --__init__.py
    - --dev.py
    - --prod.py
  - --mainapp:
      - --__init__.py
      - --models.py
      - --views.py
      - --templates:
            - --base.html
            - --index.html
  - --adminapp:
      - --test.py
      - --admin_config:
          - --root:
              - --login.txt
              - --pass.txt
              - --default_user:
                - --login.txt
                - --pass.txt
  - --authapp:
      - --__init__.py
      - --models.py
      - --views.py
      - --templates:
            - --test.html
            - --pattern.html